# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MagicBullet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MagicBullet
  pod 'LayoutKit'
  pod 'YogaKit', '~> 1.5'
  target 'MagicBulletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MagicBulletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
